//package helloworld;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//
//@DynamoDBTable(tableName = "Music")
//public class Music {
//    private String SongTitle;
//    private String Artist;
//
//
//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
//    public String getSongTitle() {
//        return SongTitle;
//    }
//    public void setSongTitle(String songTitle) {}
//
//    @DynamoDBAttribute
//    public String getArtist() {
//        return Artist;
//    }
//
//    public void setArtist(String artist) {
//        Artist = artist;
//    }
//
//}
